FROM python:latest

WORKDIR /app

RUN pip install gunicorn uvicorn

COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

COPY ./ /app/

EXPOSE 8000

RUN python manage.py migrate