# Generated by Django 5.1.2 on 2024-12-08 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(upload_to='posts/')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('media_type', models.CharField(choices=[('vidoe', 'vidoe'), ('image', 'image')], max_length=300)),
            ],
        ),
    ]
