import { ReactNode } from "react";

export const metadata = {
  title: "Profile - Settings",
  description: "Generated by create next app",
};
type LayoutProps = {
  children: ReactNode; // Type the children prop
};
export default function Layout({ children }: LayoutProps) {
  return children;
}
