import { Nav } from "@/components/Nav";
import { Footer } from "@/components/Footer";
import { ContextProvider } from "@/context/contextProvider";

export const metadata = {
  title: "Home | PlanetGames",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <script src="https://cdn.tailwindcss.com" async></script>
      </head>
      <body className="bg-white relative">
        <ContextProvider>
          <Nav />
          <main className="min-h-[77vh]">{children}</main>

          <Footer />
        </ContextProvider>
      </body>
    </html>
  );
}
